llm:
  name: openai
  base_url: "https://api.gptsapi.net/v1"
  api_key: "sk-2T06b7c7f9c3870049fbf8fada596b0f8ef908d1e233KLY2"
  model_name: "gpt-4.1-mini"

embedding:
  name: huggingface
  model_name: "/finance_ML/dataarc_syn_database/model/Qwen/qwen_embedding_0.6B"
  model_kwargs:
    device: "cuda:7"
  encode_kwargs:
    batch_size: 8



# store:
#   name: faiss
#   folder_path: /data/FinAi_Mapping_Knowledge/chenmingzhen/test_faiss_store

store:
  name: faiss
  folder_path: /data/FinAi_Mapping_Knowledge/liuyingqi/test_faiss_store_commentary


# bm25:
#   name: bm25
#   k: 10
#   data_path: /data/FinAi_Mapping_Knowledge/chenmingzhen/tog3_backend/TCL/syn_table_data/data_all_clearn_short_chunk_with_caption_desc.json

bm25:
  name: bm25
  k: 10
  data_path: /data/FinAi_Mapping_Knowledge/liuyingqi/中公-2025国考申论教材.json


retriever:
  name: vectorstore

reranker:
  name: qwen3
  model_name_or_path: "/finance_ML/dataarc_syn_database/model/Qwen/qwen_reranker_0.6B"
  device_id: "cuda:7"

dataset:
  name: TCL
  
rewrite:
  path: /data/FinAi_Mapping_Knowledge/liuyingqi/commentary_test/rewrite_query.json